name: update_homebrew

publish_to: none
environment:
  sdk: ^3.8.0

dependencies:
  _discoveryapis_commons: ^1.0.7
  args: ^2.7.0
  googleapis: ^15.0.0
  http: ^1.6.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  test: ^1.29.0

dev_dependencies:
  lints: ^6.1.0
